null = None; true = True; false = False;
#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/

synths_names = {
  ":dull_bell": "DullBell",
  ":pretty_bell": "PrettyBell",
  ":beep": "Beep",
  ":sine": "Beep",
  ":saw": "Saw",
  ":pulse": "Pulse",
  ":subpulse": "SubPulse",
  ":square": "Square",
  ":tri": "Tri",
  ":dsaw": "DSaw",
  ":dpulse": "DPulse",
  ":dtri": "DTri",
  ":fm": "FM",
  ":mod_fm": "ModFM",
  ":mod_saw": "ModSaw",
  ":mod_dsaw": "ModDSaw",
  ":mod_sine": "ModSine",
  ":mod_beep": "ModSine",
  ":mod_tri": "ModTri",
  ":mod_pulse": "ModPulse",
  ":chiplead": "ChipLead",
  ":chipbass": "ChipBass",
  ":tb303": "TB303",
  ":supersaw": "Supersaw",
  ":hoover": "Hoover",
  ":prophet": "Prophet",
  ":zawa": "Zawa",
  ":dark_ambience": "DarkAmbience",
  ":growl": "Growl",
  ":hollow": "Hollow",
  ":mono_player": "MonoPlayer",
  ":stereo_player": "StereoPlayer",
  ":blade": "SynthViolin",
  ":piano": "SynthPiano",
  ":rodeo": "SynthRodeo",
  ":kalimba": "SynthKalimba",
  ":pluck": "SynthPluck",
  ":tech_saws": "TechSaws",
  ":sound_in": "SoundIn",
  ":sound_in_stereo": "SoundInStereo",
  ":noise": "Noise",
  ":pnoise": "PNoise",
  ":bnoise": "BNoise",
  ":gnoise": "GNoise",
  ":cnoise": "CNoise",
  ":chipnoise": "ChipNoise",
  ":basic_mono_player": "BasicMonoPlayer",
  ":basic_stereo_player": "BasicStereoPlayer",
  ":basic_mixer": "BasicMixer",
  ":main_mixer": "MainMixer"
}

