null = None; true = True; false = False;
#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/

funct_doc = {
  "all_sample_names": {},
  "chord": {},
  "chord_degree": {},
  "chord_invert": {},
  "chord_names": {},
  "control": {},
  "current_arg_checks": {},
  "current_cent_tuning": {},
  "current_debug": {},
  "current_octave": {},
  "current_sample_defaults": {},
  "current_sched_ahead_time": {},
  "current_synth": {},
  "current_synth_defaults": {},
  "current_transpose": {},
  "current_volume": {},
  "degree": {},
  "fx_names": {},
  "hz_to_midi": {},
  "kill": {},
  "load_sample": {},
  "load_samples": {},
  "load_synthdefs": {},
  "midi_notes": {},
  "midi_to_hz": {},
  "note": {},
  "note_info": {},
  "note_range": {},
  "octs": {},
  "pitch_to_ratio": {},
  "play": {},
  "play_chord": {},
  "play_pattern": {},
  "play_pattern_timed": {},
  "ratio_to_pitch": {},
  "recording_delete": {},
  "recording_save": {},
  "recording_start": {},
  "recording_stop": {},
  "reset_mixer!": {},
  "rest?": {},
  "sample_buffer": {},
  "sample_free": {},
  "sample_free_all": {},
  "sample_groups": {},
  "sample_info": {},
  "sample_names": {},
  "sample_paths": {},
  "scale": {},
  "scale_names": {},
  "set_cent_tuning!": {},
  "set_control_delta!": {},
  "set_mixer_control!": {},
  "set_sched_ahead_time!": {},
  "set_volume!": {},
  "status": {},
  "synth": {},
  "synth_names": {},
  "use_arg_bpm_scaling": {},
  "use_arg_checks": {},
  "use_cent_tuning": {},
  "use_debug": {},
  "use_merged_sample_defaults": {},
  "use_merged_synth_defaults": {},
  "use_octave": {},
  "use_sample_bpm": {},
  "use_sample_defaults": {},
  "use_synth": {},
  "use_synth_defaults": {},
  "use_timing_guarantees": {},
  "use_transpose": {},
  "use_tuning": {},
  "with_arg_bpm_scaling": {},
  "with_arg_checks": {},
  "with_cent_tuning": {},
  "with_debug": {},
  "with_fx": {},
  "with_merged_sample_defaults": {},
  "with_merged_synth_defaults": {},
  "with_octave": {},
  "with_sample_bpm": {},
  "with_sample_defaults": {},
  "with_synth": {},
  "with_synth_defaults": {},
  "with_timing_guarantees": {},
  "with_transpose": {},
  "with_tuning": {}
}
#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/#\#/

opts_doc = {
  "amp": "The amplitude of the note",
  "amp_slide": "The duration in beats for amplitude changes to take place",
  "attack": "Amount of time (in beats) for sound to reach full amplitude (attack_level). A short attack (i.e. 0.01) makes the initial part of the sound very percussive like a sharp tap. A longer attack (i.e 1) fades the sound in gently.",
  "attack_level": "Amplitude level reached after attack phase and immediately before decay phase",
  "decay": "Amount of time (in beats) for the sound to move from full amplitude (attack_level) to the sustain amplitude (sustain_level).",
  "decay_level": "Amplitude level reached after decay phase and immediately before sustain phase. Defaults to sustain_level unless explicitly set",
  "env_curve": "Select the shape of the curve between levels in the envelope. 1=linear, 2=exponential, 3=sine, 4=welch, 6=squared, 7=cubed",
  "on": "If specified and false/nil/0 will stop the synth from being played. Ensures all opts are evaluated.",
  "pan": "The stereo position of the sound. -1 is left, 0 is in the middle and 1 is on the right. You may use a value in between -1 and 1 such as 0.25",
  "pan_slide": "The duration in beats for the pan value to change",
  "pitch": "Pitch adjustment in semitones. 1 is up a semitone, 12 is up an octave, -12 is down an octave etc.  Decimal numbers can be used for fine tuning.",
  "release": "Amount of time (in beats) for sound to move from sustain level amplitude to silent. A short release (i.e. 0.01) makes the final part of the sound very percussive (potentially resulting in a click). A longer release (i.e 1) fades the sound out gently.",
  "slide": "Default slide time in beats for all slide opts. Individually specified slide opts will override this value",
  "sustain": "Amount of time (in beats) for sound to remain at sustain level amplitude. Longer sustain values result in longer sounds. Full length of sound is attack + decay + sustain + release.",
  "sustain_level": "Amplitude level reached after decay phase and immediately before release phase."
}
